app = "ai-web-app-backend"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8000"
  ENVIRONMENT = "production"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512MB"

[deploy]
  strategy = "rolling"